config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 5}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @heading = 'Правила анекдотного клуба'
    @text1 = 'Первое правило андекдотного клуба: никому не рассказывать об анекдотном клубе.'
    @text2 = 'Второе правило андекдотного клуба: никогда никому не рассказывать об анекдотном клубе.'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @post = Post.all
  end

  def new
    @post = current_user.posts.build
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if(@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])

    @post.destroy
    redirect_to posts_path
  end

  def create
    # render plain: params[:post].inspect
    @post = current_user.posts.build(post_params)

    if(@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simpleblog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-bold">AnClub</h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <% if user_signed_in? %>
      <span class="p-2 text-dark"><%= link_to "Выйти", destroy_user_session_path, method: :delete %></span>
      <% else %>
      <span class="p-2 text-dark"><%= link_to "Войти", new_user_session_path %></span>
      <span class="p-2 text-dark"><%= link_to "Зарегистрироваться", new_user_registration_path %></span>
      <% end %>
    <span class="p-2 text-dark"><%= link_to "Каталог анекдотов", home_path %></span>
    <span class="p-2 text-dark"><%= link_to "Правила клуба", about_path %></span>
  </nav>
  <span class="btn btn-outline-primary" ><%= link_to "Добавление анекдота", new_post_path %></span>
</div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>


<div class = "container">
  <%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1><%= @heading %></h1>
<p><%= @text1 %></p>
<p><%= @text2 %></p>

app/views/posts/edit.html.erb
<h2>Редактирование анекдота</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
    <%@post.errors.full_messages.each do |msg| %>
      <div class = "allert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    Название<br>
    <%= f.text_field (:title) %>
  </p>

  <p>
    Анекдот<br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit%>
  </p>

<% end %>

app/views/posts/index.html.erb
<h1>Все Анекдоты</h1>
<% @post.each do |post| %>
  <div class="well">
    <h3><%= post.title %></h3>
    <p><%= post.body %></p>
    <p>
      Автор:
      <%= post.user.email %>
    </p>
    <%= link_to "Читать далее", post_path(post), :class => 'btn btn-outline-primary' %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h2>Добавление нового анекдота</h2>
<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
    <%@post.errors.full_messages.each do |msg| %>
      <div class = "allert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    Название<br>
    <%= f.text_field (:title) %>
  </p>

  <p>
    Анекдот<br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<% if @post.user == current_user %>
<hr>
<%= link_to "Редактировать", edit_post_path(@post), :class => 'btn btn-warning' %>
<%= link_to "Удалить", post_path(@post), method: :delete, data:{confirm:"Хотите удалить анекдот?"},:class => 'btn btn-danger' %>
<hr>
<% end %>